# Generated by Django 3.1 on 2020-08-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='TypePersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование должности')),
                ('slug', models.CharField(max_length=100, verbose_name='Код должности')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория товара')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('article', models.IntegerField(verbose_name='код товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.typeproduct', verbose_name='тип товара')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.personal', verbose_name='сотрудник')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.typeproduct', verbose_name='категория товара')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.typepersonal', verbose_name='должность'),
        ),
    ]
